# TCL File Generated by Component Editor 14.0
# Thu Mar 17 16:38:07 EDT 2016
# DO NOT MODIFY


# 
# ECCDH3DES_fpga "ECCDH3DES_fpga" v1.0
# Xiongyao Zha, Manish Gupta 2016.03.17.16:38:07
# FPGA wrapper for ECCDH3DES chip on the Avalon Bus.
# 

# 
# request TCL package from ACDS 14.0
# 
package require -exact qsys 14.0


# 
# module ECCDH3DES_fpga
# 
set_module_property DESCRIPTION "FPGA wrapper for ECCDH3DES chip on the Avalon Bus."
set_module_property NAME ECCDH3DES_fpga
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Xiongyao Zha, Manish Gupta"
set_module_property DISPLAY_NAME ECCDH3DES_fpga
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ECCDH3DES_fpga
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ECCDH3DES_fpga.sv SYSTEM_VERILOG PATH ../source/ECCDH3DES_fpga.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL ECCDH3DES_fpga
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ECCDH3DES_fpga.sv SYSTEM_VERILOG PATH ../source/ECCDH3DES_fpga.sv


# 
# parameters
# 
add_parameter SLAVE_ADDRESSWIDTH INTEGER 8
set_parameter_property SLAVE_ADDRESSWIDTH DEFAULT_VALUE 8
set_parameter_property SLAVE_ADDRESSWIDTH DISPLAY_NAME SLAVE_ADDRESSWIDTH
set_parameter_property SLAVE_ADDRESSWIDTH TYPE INTEGER
set_parameter_property SLAVE_ADDRESSWIDTH UNITS None
set_parameter_property SLAVE_ADDRESSWIDTH HDL_PARAMETER true
add_parameter DATAWIDTH INTEGER 32
set_parameter_property DATAWIDTH DEFAULT_VALUE 32
set_parameter_property DATAWIDTH DISPLAY_NAME DATAWIDTH
set_parameter_property DATAWIDTH TYPE INTEGER
set_parameter_property DATAWIDTH UNITS None
set_parameter_property DATAWIDTH HDL_PARAMETER true
add_parameter NUMREGS INTEGER 256
set_parameter_property NUMREGS DEFAULT_VALUE 256
set_parameter_property NUMREGS DISPLAY_NAME NUMREGS
set_parameter_property NUMREGS TYPE INTEGER
set_parameter_property NUMREGS UNITS None
set_parameter_property NUMREGS HDL_PARAMETER true
add_parameter REGWIDTH INTEGER 32
set_parameter_property REGWIDTH DEFAULT_VALUE 32
set_parameter_property REGWIDTH DISPLAY_NAME REGWIDTH
set_parameter_property REGWIDTH TYPE INTEGER
set_parameter_property REGWIDTH UNITS None
set_parameter_property REGWIDTH HDL_PARAMETER true
add_parameter ADDRSIZE INTEGER 14
set_parameter_property ADDRSIZE DEFAULT_VALUE 14
set_parameter_property ADDRSIZE DISPLAY_NAME ADDRSIZE
set_parameter_property ADDRSIZE TYPE INTEGER
set_parameter_property ADDRSIZE UNITS None
set_parameter_property ADDRSIZE HDL_PARAMETER true
add_parameter SRAMWIDTH INTEGER 64
set_parameter_property SRAMWIDTH DEFAULT_VALUE 64
set_parameter_property SRAMWIDTH DISPLAY_NAME SRAMWIDTH
set_parameter_property SRAMWIDTH TYPE INTEGER
set_parameter_property SRAMWIDTH UNITS None
set_parameter_property SRAMWIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock
set_interface_property avalon_slave associatedReset reset
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave slave_address address Input SLAVE_ADDRESSWIDTH
add_interface_port avalon_slave slave_chipselect chipselect Input 1
add_interface_port avalon_slave slave_write write Input 1
add_interface_port avalon_slave slave_writedata writedata Input DATAWIDTH
add_interface_port avalon_slave slave_readdata readdata Output DATAWIDTH
add_interface_port avalon_slave slave_read read Input 1
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0

